<a href="https://colab.research.google.com/github/ParhamPishro/Flavonoid/blob/main/1%20Data%20Collection/CV_Values_for_Studies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Read Data

df = pd.read_excel("/content/CV.xlsx")
df

,authors,flavonoid,cell line,time,dose,viability-mean,viability-error,viability-SD,viability-SE
0,Wang et al. 2011,Chrysin,KYSE510,24,20,77.142857,79.507389,2.364532,NaN
1,Wang et al. 2011,Chrysin,KYSE510,24,40,52.679803,67.162562,14.482759,NaN
2,Wang et al. 2011,Chrysin,KYSE510,24,80,36.354680,37.536946,1.182266,NaN
3,Wang et al. 2011,Chrysin,KYSE510,48,10,83.349754,85.123153,1.773399,NaN
4,Wang et al. 2011,Chrysin,KYSE510,48,20,68.275862,68.275862,0.001000,NaN
...,...,...,...,...,...,...,...,...,...
311,Zhang et al. 2009,Myricetin,KYSE510,48,80,46.442308,49.326923,2.884615,2.884615
312,Zhang et al. 2009,Myricetin,KYSE510,72,10,69.230769,72.403846,3.173077,3.173077
313,Zhang et al. 2009,Myricetin,KYSE510,72,20,65.480769,70.384615,4.903846,4.903846
314,Zhang et al. 2009,Myricetin,KYSE510,72,40,46.153846,48.750000,2.596154,2.596154
315,Zhang et al. 2009,Myricetin,KYSE510,72,80,32.596154,34.615385,2.019231,2.019231

In [ ]:
# Select "Does=40" Rows

df_40 = df[df['dose']==40]
df_40

,authors,flavonoid,cell line,time,dose,viability-mean,viability-error,viability-SD,viability-SE
1,Wang et al. 2011,Chrysin,KYSE510,24,40,52.679803,67.162562,14.482759,NaN
5,Wang et al. 2011,Chrysin,KYSE510,48,40,44.630542,45.812808,1.182266,NaN
9,Wang et al. 2011,Chrysin,KYSE510,72,40,29.556650,30.443350,0.886700,NaN
12,Wang et al. 2011,Kaempferol,KYSE510,24,40,75.000000,77.100000,2.100000,2.100000
16,Wang et al. 2011,Kaempferol,KYSE510,48,40,49.900000,51.100000,1.200000,1.200000
...,...,...,...,...,...,...,...,...,...
300,Zhang et al. 2009,Kaempferol,KYSE510,48,40,35.825243,38.446602,2.621359,2.621359
304,Zhang et al. 2009,Kaempferol,KYSE510,72,40,27.378641,29.417476,2.038835,2.038835
306,Zhang et al. 2009,Myricetin,KYSE510,24,40,95.769231,99.230769,3.461538,3.461538
310,Zhang et al. 2009,Myricetin,KYSE510,48,40,57.980769,62.884615,4.903846,4.903846
314,Zhang et al. 2009,Myricetin,KYSE510,72,40,46.153846,48.750000,2.596154,2.596154

In [ ]:
# 1st, 2nd, and 3rd Column

df_40[['authors', 'flavonoid', 'cell line', 'time', 'viability-mean']].groupby(['authors', 'flavonoid', 'cell line']).size()

authors               flavonoid   cell line
Wang et al. 2011      Chrysin     KYSE510      3
                      Kaempferol  KYSE510      3
Wang et al. 2011 (2)  Chrysin     OE33         3
                      Kaempferol  OE33         2
Xin 2008              Apigenin    KYSE510      3
                                  OE33         3
                      Chrysin     KYSE510      3
                                  OE33         3
                      Kaempferol  KYSE510      3
                                  OE33         3
                      Luteolin    KYSE510      3
                                  OE33         3
                      Myricetin   KYSE510      2
                                  OE33         3
                      Quercetin   KYSE510      3
                                  OE33         3
Zhang et al. 2008     Apigenin    OE33         3
                      Chrysin     OE33         3
                      Kaempferol  OE33         3
                      Luteolin    OE33         3
                      Myricetin   OE33         3
                      Quercetin   OE33         3
Zhang et al. 2009     Apigenin    KYSE510      3
                      Chrysin     KYSE510      3
                      Kaempferol  KYSE510      3
                      Luteolin    KYSE510      3
                      Myricetin   KYSE510      3
                      Quercetin   KYSE510      3
dtype: int64

In [ ]:
# Mean for Two Last Columns

mean_ = df_40[['flavonoid', 'cell line', 'time', 'viability-mean']].groupby(['flavonoid', 'cell line', 'time']).mean()
mean_

                           viability-mean
flavonoid  cell line time
Apigenin   KYSE510   24         91.706517
                     48         43.416208
                     72         35.423191
           OE33      24         71.548561
                     48         66.595369
                     72         68.155813
Chrysin    KYSE510   24         60.797562
                     48         36.062526
                     72         22.526137
           OE33      24         67.768476
                     48         55.832380
                     72         49.375271
Kaempferol KYSE510   24         73.782566
                     48         40.661412
                     72         41.590962
           OE33      24         76.314486
                     48         67.281682
                     72         53.870215
Luteolin   KYSE510   24         41.087070
                     48         15.451512
                     72          2.882169
           OE33      24         60.757742
                     48         47.492571
                     72         42.509775
Myricetin  KYSE510   24         95.769231
                     48         58.237696
                     72         46.087676
           OE33      24         83.518898
                     48         66.597582
                     72         66.597984
Quercetin  KYSE510   24         51.382353
                     48         16.525210
                     72          2.970588
           OE33      24         58.681274
                     48         47.467409
                     72         40.215633

In [ ]:
# STD for Two Last Columns

std_ = df_40[['flavonoid', 'cell line', 'time', 'viability-mean']].groupby(['flavonoid', 'cell line', 'time']).std()
std_

                           viability-mean
flavonoid  cell line time
Apigenin   KYSE510   24          0.333654
                     48          0.255851
                     72          0.649353
           OE33      24          0.821402
                     48          0.507433
                     72          0.327085
Chrysin    KYSE510   24          7.036017
                     48          7.420397
                     72          6.090543
           OE33      24          4.532109
                     48         10.365135
                     72          0.227546
Kaempferol KYSE510   24          1.077905
                     48          8.003791
                     72         24.776325
           OE33      24          4.601045
                     48          6.471341
                     72          5.916842
Luteolin   KYSE510   24          0.527196
                     48          0.032443
                     72          0.772730
           OE33      24          0.149295
                     48          0.625381
                     72          0.293614
Myricetin  KYSE510   24               NaN
                     48          0.363350
                     72          0.093579
           OE33      24          0.152799
                     48          0.097700
                     72          0.341383
Quercetin  KYSE510   24          0.540729
                     48          0.338698
                     72          0.041595
           OE33      24          0.263964
                     48          0.402503
                     72          0.304952

In [ ]:
# Two Last Columns

std_ / mean_

                           viability-mean
flavonoid  cell line time
Apigenin   KYSE510   24          0.003638
                     48          0.005893
                     72          0.018331
           OE33      24          0.011480
                     48          0.007620
                     72          0.004799
Chrysin    KYSE510   24          0.115729
                     48          0.205765
                     72          0.270377
           OE33      24          0.066876
                     48          0.185647
                     72          0.004609
Kaempferol KYSE510   24          0.014609
                     48          0.196840
                     72          0.595714
           OE33      24          0.060291
                     48          0.096183
                     72          0.109835
Luteolin   KYSE510   24          0.012831
                     48          0.002100
                     72          0.268107
           OE33      24          0.002457
                     48          0.013168
                     72          0.006907
Myricetin  KYSE510   24               NaN
                     48          0.006239
                     72          0.002030
           OE33      24          0.001830
                     48          0.001467
                     72          0.005126
Quercetin  KYSE510   24          0.010524
                     48          0.020496
                     72          0.014002
           OE33      24          0.004498
                     48          0.008480
                     72          0.007583